server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:contribution-service
  cloud:
    discovery:
      enabled: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  config:
    import: optional:configserver:http://localhost:8090

eureka:
  instance:
    prefer-ip-address: true
